.PHONY: lint test install-tools

lint:
	go fmt ./...
	go vet ./...
	revive -config revive.toml -formatter friendly ./...

test:
	go test -race -count=1 ./...

install-tools:
	go install github.com/mgechev/revive
